print(1 % 3)
print(1 | 3)

print(1 & 2)
print(1 | 2)

print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("-" * 20)
print(True or True)
print(True or False)
print(False and True)
print(False and False)
